### ISSUE TITLE
Symbolic links do not work under Windows

### ISSUE THREAD

**Issue by kelemeng** [WollMux/wollmux-config#2]
I tried to use the wollmux-config under Windows (zip extraction failed in 7zip, but succeeded in cygwin - only it does not work), but got errors related to symbolically linked items.

![wollmux-error](https://user-images.githubusercontent.com/314822/200313110-f9f6c19f-3e44-4383-8ea2-d2409b473284.png)
[wollmux-confiv-output.txt](https://github.com/WollMux/wollmux-config/files/9951655/wollmux-confiv-output.txt)

**Comment by smehrbrodt** [comment]
Extracting https://github.com/WollMux/wollmux-config/releases/download/v18.1.0/wollmux-config-18.1.0.7z to my user profile on Windows (using 7zip) works flawlessly - the `.wollmux\config\vorlagen\standard\X.buttons\30.Externer Briefkopf.ott` is a regular file.
Wollmux works and opening the "Externer Briefkopf" from the sidebar also works.

Can you try again? Is it maybe some problem with the locale you are using?

**Comment by smehrbrodt** [comment]
.tar.gz doesn't work on Windows, but 7zip does.
