### ISSUE TITLE
Move essential parts of config to WollMux proper

### ISSUE THREAD

**Issue by kelemeng** [WollMux/wollmux-config#3]
As part of making WollMux more widely deployable, it may make sense to move some of the essential configurations into the extension itself, so that it is shipped with a bare minimum of features that would fit every use case.
This would make the config contain only the deployment-specific optional stuff such as document templates and customizations.
![wollmux-conf](https://user-images.githubusercontent.com/314822/200512873-3dc90277-36e6-4e2b-b1c3-9b24a9ee466d.png)

**Comment by smehrbrodt** [comment]
I moved the translations out of the config with commit 6d5099246b295ff666cbf66ed3bb11d209977961 .
The rest *is* deployment specific.

However, I also improved the warning like this:
![grafik](https://user-images.githubusercontent.com/3502738/208400645-3da8805a-6558-464d-b001-c4f276f1fd14.png)

This should make it easier for new users to discover how to setup the config.

Bundling the example config might be an option, but that requires more thought and structural changes in WollMux.
Also we need to keep in mind that config files can also be served via [remote service](https://github.com/WollMux/wollmux-conf-service).
